import { useState } from "react"
import axios from "axios"
import Head from "next/head"
import { BsSearch } from "react-icons/bs"

export default function Home() {
  const [city, setCity] = useState("")
  const [weather, setWeather] = useState({})
  const [loading, seLoading] = useState(false)

  const url = `https://api.openweathermap.org/data/2.5/weather?q={city name}&appid=${process.env.NEXT_PUBLIC_WEATHER_API_KEY}`

  const feathWeather = (e) => {
    e.preventDefault()
    seLoading(true)
    axios.get(url).then((res) => {
      setWeather(res.data)
      console.log(res.data)
    })
    setCity("")
    seLoading(false)
  }
  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={feathWeather}>Feath</button>
    </div>
  )
}
